site_name: Design Patterns

site_url: http://127.0.0.1:8000/mkdocs

theme:
  logo: https://cdn-icons-png.flaticon.com/512/2500/2500198.png
  name: material
  features:
    - content.code.select
    - content.code.copy
  palette: 
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - offline:
      enabled: true
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Creational:
    - Builder: creational/builder.md
    - Factory Method: creational/factory-method.md
  - Structural:
    - Adapter: structural/adapter.md
    - Facade: structural/facade.md
    - Decorator: structural/decorator.md
  - Behavioral:
    - Observer: behavioral/observer.md
    - Strategy: behavioral/strategy.md
    - State: behavioral/state.md